# -*- coding: utf-8 -*-
"""
Face descriptions.
"""

face_features = {
'face000.bmp': ('Male',  'Blue',  'Good'),
'face001.bmp': ('Male',  'Blue',  'Good'),
'face002.bmp': ('Male',  'Blue',  'Good'),
'face003.bmp': ('Male',  'Blue',  'Good'),
'face004.bmp': ('Male',  'Blue',  'Good'),
'face005.bmp': ('Male',  'Blue',  'Good'),
'face006.bmp': ('Male',  'Blue',  'Good'),
'face007.bmp': ('Female','Brown', 'Good'),
'face008.bmp': ('Male',  'Blue',  'Good'),
'face009.bmp': ('Male',  'Blue',  'Good'),
'face010.bmp': ('Male',  'Blue',  'Good'),
'face011.bmp': ('Male',  'Blue',  'Evil'),
'face012.bmp': ('Female','Blue',  'Good'),
'face013.bmp': ('Female','Blue',  'Good'),
'face014.bmp': ('Female','Blue',  'Evil'),
'face015.bmp': ('Female','Brown', 'Good'),
'face016.bmp': ('Female','Brown', 'Good'),
'face017.bmp': ('Female','Brown', 'Evil'),
'face018.bmp': ('Female','Brown', 'Evil'),
'face019.bmp': ('Female','Brown', 'Evil'),
'face020.bmp': ('Female','Brown', 'Good'),
'face021.bmp': ('Female','Brown', 'Evil'),
'face022.bmp': ('Female','Brown', 'Good'),
'face023.bmp': ('Female','Brown', 'Good'),
'face024.bmp': ('Female','Brown', 'Good'),
'face025.bmp': ('Female','Brown', 'Good'),
'face026.bmp': ('Female','Brown', 'Evil'),
'face027.bmp': ('Female','Brown', 'Evil'),
'face028.bmp': ('Female','Brown', 'Good'),
'face029.bmp': ('Female','Brown', 'Evil'),
'face030.bmp': ('Female','Brown', 'Evil'),
'face031.bmp': ('Female','Blue',  'Good'),
'face032.bmp': ('Female','Brown', 'Good'),
'face033.bmp': ('Female','Brown', 'Evil'),
'face034.bmp': ('Female','Brown', 'Good'),
'face035.bmp': ('Female','Brown', 'Evil'),
'face036.bmp': ('Female','Brown', 'Good'),
'face037.bmp': ('Female','Brown', 'Good'),
'face038.bmp': ('Female','Blue',  'Evil'),
'face039.bmp': ('Male',  'Blue',  'Good'),
'face040.bmp': ('Male',  'Blue',  'Good'),
'face041.bmp': ('Female','Blue',  'Good'),
'face042.bmp': ('Male',  'Blue',  'Good'),
'face043.bmp': ('Female','Blue',  'Good'),
'face044.bmp': ('Male',  'Brown', 'Good'),
'face045.bmp': ('Male',  'Brown', 'Good'),
'face046.bmp': ('Male',  'Brown', 'Good'),
'face047.bmp': ('Male',  'Brown', 'Good'),
'face048.bmp': ('Male',  'Brown', 'Evil'),
'face049.bmp': ('Male',  'Brown', 'Good'),
'face050.bmp': ('Male',  'Brown', 'Evil'),
'face051.bmp': ('Male',  'Brown', 'Good'),
'face052.bmp': ('Male',  'Brown', 'Good'),
'face053.bmp': ('Male',  'Brown', 'Good'),
'face054.bmp': ('Male',  'Brown', 'Good'),
'face055.bmp': ('Male',  'Brown', 'Good'),
'face056.bmp': ('Male',  'Brown', 'Evil'),
'face057.bmp': ('Male',  'Blue',  'Good'),
'face058.bmp': ('Male',  'Blue',  'Good'),
'face059.bmp': ('Male',  'Brown', 'Good'),
'face060.bmp': ('Male',  'Brown', 'Evil'),
'face061.bmp': ('Male',  'Brown', 'Good'),
'face062.bmp': ('Male',  'Blue',  'Good'),
'face063.bmp': ('Male',  'Blue',  'Good'),
'face064.bmp': ('Male',  'Brown', 'Good'),
'face065.bmp': ('Male',  'Blue',  'Good'),
'face066.bmp': ('Male',  'Blue',  'Evil'),
'face067.bmp': ('Male',  'Blue',  'Good'),
'face068.bmp': ('Male',  'Blue',  'Good'),
'face069.bmp': ('Male',  'Blue',  'Good'),
'face070.bmp': ('Female','Blue',  'Good'),
'face071.bmp': ('Female','Blue',  'Good'),
'face072.bmp': ('Female','Blue',  'Good'),
'face073.bmp': ('Female','Brown', 'Evil'),
'face074.bmp': ('Female','Brown', 'Evil'),
'face075.bmp': ('Female','Blue',  'Good'),
'face076.bmp': ('Female','Brown', 'Evil'),
'face077.bmp': ('Female','Brown', 'Evil'),
'face078.bmp': ('Female','Blue',  'Evil'),
'face079.bmp': ('Female','Brown', 'Good'),
'face080.bmp': ('Female','Blue',  'Evil'),
'face081.bmp': ('Female','Brown', 'Evil'),
'face082.bmp': ('Female','Brown', 'Good'),
'face083.bmp': ('Female','Brown', 'Evil'),
'face084.bmp': ('Female','Brown', 'Good'),
'face085.bmp': ('Female','Brown', 'Good'),
'face086.bmp': ('Female','Brown', 'Good'),
'face087.bmp': ('Female','Brown', 'Good'),
'face088.bmp': ('Male',  'Brown', 'Good'),
'face089.bmp': ('Male',  'Brown', 'Good'),
'face090.bmp': ('Male',  'Blue',  'Good'),
'face091.bmp': ('Male',  'Blue',  'Good'),
'face092.bmp': ('Female','Brown', 'Evil'),
'face093.bmp': ('Male',  'Blue',  'Good'),
'face094.bmp': ('Male',  'Brown', 'Good'),
'face095.bmp': ('Male',  'Brown', 'Good'),
'face096.bmp': ('Female','Brown', 'Good'),
'face097.bmp': ('Male',  'Blue',  'Good'),
'face098.bmp': ('Male',  'Brown', 'Good'),
'face099.bmp': ('Male',  'Blue',  'Good'),
'face100.bmp': ('Male',  'Blue',  'Good'),
'face101.bmp': ('Male',  'Blue',  'Good'),
'face102.bmp': ('Male',  'Blue',  'Good'),
'face103.bmp': ('Male',  'Blue',  'Good'),
'face104.bmp': ('Female','Brown', 'Good'),
'face105.bmp': ('Female','Brown', 'Good'),
'face106.bmp': ('Female','Brown', 'Evil'),
'face107.bmp': ('Female','Brown', 'Evil'),
'face108.bmp': ('Female','Brown', 'Good'),
'face109.bmp': ('Female','Brown', 'Good'),
'face110.bmp': ('Female','Brown', 'Good'),
'face111.bmp': ('Female','Brown', 'Evil'),
'face112.bmp': ('Female','Brown', 'Good'),
'face113.bmp': ('Female','Brown', 'Good'),
'face114.bmp': ('Female','Brown', 'Evil'),
'face115.bmp': ('Female','Brown', 'Evil'),
'face116.bmp': ('Female','Brown', 'Good'),
'face117.bmp': ('Female','Brown', 'Good'),
'face118.bmp': ('Female','Brown', 'Good'),
'face119.bmp': ('Female','Brown', 'Good'),
'face120.bmp': ('Female','Brown', 'Good'),
'face121.bmp': ('Female','Blue',  'Evil'),
'face122.bmp': ('Female','Blue',  'Evil'),
'face123.bmp': ('Female','Brown', 'Good'),
'face124.bmp': ('Female','Brown', 'Evil'),
'face125.bmp': ('Female','Brown', 'Good'),
'face126.bmp': ('Female','Brown', 'Good'),
'face127.bmp': ('Female','Brown', 'Evil'),
'face128.bmp': ('Male',  'Brown', 'Good'),
'face129.bmp': ('Male',  'Blue',  'Good'),
'face130.bmp': ('Male',  'Blue',  'Good'),
'face131.bmp': ('Female','Blue',  'Good'),
'face132.bmp': ('Female','Blue',  'Good'),
'face133.bmp': ('Female','Brown', 'Evil'),
'face134.bmp': ('Male',  'Brown', 'Evil'),
'face135.bmp': ('Male',  'Brown', 'Good'),
'face136.bmp': ('Male',  'Brown', 'Good'),
'face137.bmp': ('Male',  'Brown', 'Good'),
'face138.bmp': ('Male',  'Brown', 'Good'),
'face139.bmp': ('Male',  'Brown', 'Good'),
'face140.bmp': ('Male',  'Brown', 'Evil'),
'face141.bmp': ('Male',  'Brown', 'Good'),
'face142.bmp': ('Male',  'Brown', 'Evil'),
'face143.bmp': ('Male',  'Brown', 'Good'),
'face144.bmp': ('Male',  'Brown', 'Evil'),
'face145.bmp': ('Male',  'Brown', 'Good'),
'face146.bmp': ('Male',  'Brown', 'Evil'),
'face147.bmp': ('Male',  'Brown', 'Good'),
'face148.bmp': ('Male',  'Brown', 'Good'),
'face149.bmp': ('Male',  'Brown', 'Evil'),
'face150.bmp': ('Male',  'Brown', 'Good'),
'face151.bmp': ('Female','Blue',  'Good'),
'face152.bmp': ('Male',  'Blue',  'Good'),
'face153.bmp': ('Female','Blue',  'Good'),
'face154.bmp': ('Female','Blue',  'Evil'),
'face155.bmp': ('Female','Brown', 'Good'),
'face156.bmp': ('Female','Brown', 'Good'),
'face157.bmp': ('Female','Brown', 'Evil'),
'face158.bmp': ('Male',  'Blue',  'Good'),
'face159.bmp': ('Male',  'Brown', 'Good'),
'face160.bmp': ('Male',  'Blue',  'Good'),
'face161.bmp': ('Female','Blue',  'Good'),
'face162.bmp': ('Female','Brown', 'Evil'),
'face163.bmp': ('Female','Brown', 'Good'),
'face164.bmp': ('Female','Brown', 'Evil'),
'face165.bmp': ('Male',  'Brown', 'Evil'),
'face166.bmp': ('Female','Brown', 'Good'),
'face167.bmp': ('Female','Brown', 'Evil'),
'face168.bmp': ('Female','Brown', 'Good'),
'face169.bmp': ('Female','Brown', 'Good'),
'face170.bmp': ('Female','Brown', 'Good'),
'face171.bmp': ('Female','Blue',  'Good'),
'face172.bmp': ('Female','Blue',  'Good'),
'face173.bmp': ('Female','Brown', 'Good'),
'face174.bmp': ('Female','Brown', 'Good'),
'face175.bmp': ('Female','Brown', 'Evil'),
'face176.bmp': ('Female','Blue',  'Good'),
'face177.bmp': ('Female','Brown', 'Good') 
}

# Unusual images that can mess up the eigenstructure:
image_to_omit = {
'face011.bmp':  'strange face',
'face021.bmp':  'strange face',
'face127.bmp':  'strange face',
'face128.bmp':  'strange face',
'face024.bmp':  'teeth are showing',
'face094.bmp':  'teeth are showing',
'face128.bmp':  'teeth are showing',
'face135.bmp':  'teeth are showing',
'face147.bmp':  'teeth are showing',
'face150.bmp':  'teeth are showing' 
}

face_features_numeric = list()
for key in sorted( face_features.keys() ):
    row = list( [0,0,0] )
    if( face_features[key][0] == 'Female' ):
        row[0] = 1
    if( face_features[key][1] == 'Brown'):
        row[1] = 1
    if( face_features[key][2] == 'Evil' ):
        row[2] = 1
    face_features_numeric.append( row )
    
# Use np.array to transform face_features_numeric into an nx4 matrix.
